# SwiftLint config focado em SwiftUI

only_rules:
  # ----------- Estilo geral -----------
  - colon
  - comma
  - closing_brace
  - control_statement
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - identifier_name
  - implicit_getter
  - line_length
  - mark
  - modifier_order
  - number_separator
  - operator_usage_whitespace
  - redundant_type_annotation
  - return_arrow_whitespace
  - shorthand_operator
  - statement_position
  - syntactic_sugar
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - vertical_parameter_alignment
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

  # ----------- SwiftUI específico -----------
  - private_swiftui_state
  - private_unit_test
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_void_return

  # ----------- Custom rules -----------
  - custom_rules
  - swiftui_state_private
  - swiftui_environment_private
  - swiftui_environmentobject_private
  - swiftui_scaledtofit
  - swiftui_scaledtofill

# ----------- Config extra -----------
line_length:
  warning: 180
  error: 200

identifier_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    warning: 40
    error: 50
  allowed_symbols: ["_"]

redundant_type_annotation:
  consider_default_literal_types_redundant: true

# ----------- Regras customizadas úteis em SwiftUI -----------
custom_rules:
  swiftui_state_private:
    regex: '@State(?! private)'
    message: '@State properties devem ser private'
    severity: error

  swiftui_environment_private:
    regex: '@Environment\\(.*\\) var'
    message: '@Environment properties devem ser private'
    severity: error

  swiftui_environmentobject_private:
    regex: '@EnvironmentObject var'
    message: '@EnvironmentObject deve ser private'
    severity: error

  swiftui_scaledtofit:
    regex: 'aspectRatio\\(contentMode: \\.fit\\)'
    message: 'Prefira scaledToFit()'
    severity: warning

  swiftui_scaledtofill:
    regex: 'aspectRatio\\(contentMode: \\.fill\\)'
    message: 'Prefira scaledToFill()'
    severity: warning
